### ISSUE TITLE
Add system for flares to modify powers/spark

### ISSUE THREAD

**Issue by thomasech** [trioderegion/nova#1]
Currently setting this up for a work group, noticed that if I add a Flare like Fury, I cannot modify the Flare to add an Effect that modifies an attribute (e.g., +1 Sun) - I have to manually create the passive effect on the Actor to modify their attributes. Would be great if we could just do that within the Flare itself, similar to feats in D&D 5e system.

**Comment by trioderegion** [comment]
I agree. The flares that give +STAT are too fiddly at the moment. The second box of the attribute row (i.e. Sun  X+Y) is intended to track these bonuses for now. A better system should be implemented.  Not sure if I'm going to go the item active effect route, but it will be something a lot easier to manage for sure.

Thanks for playing with the system and providing feedback!

**Comment by trioderegion** [comment]
Progress update 
![image](https://user-images.githubusercontent.com/14878515/168493262-eab480ef-67aa-43e5-a7e0-01439336ac03.png)
