### ISSUE TITLE
Sun/Moon/Shade mods do not add up when rolling

### ISSUE THREAD

**Issue by BrotherSharper** [trioderegion/nova#10]
When creating a mod that gives a +1 to Sun/Moon/Shade, and then equipping it, it will show the correct number in the UI as being original number + augmented number as per the screenshot.
![image](https://github.com/trioderegion/nova/assets/41280723/44d0daf6-e867-45ad-9753-4f5c3286339e)

However, when rolling the appropriate attribute, it will only pick up the original number rather than the combined number of d6s.

If I remove the mod and manually change the field, it will correctly add up.
![image](https://github.com/trioderegion/nova/assets/41280723/c5eacb5f-c9ee-4366-b7bc-8e1d6c632b61)

**Comment by trioderegion** [comment]
Ahh, I see now. Thanks for the report. I bet this is an issue on Foundry v11?

**Comment by BrotherSharper** [comment]
Yep!
I am on latest V11 build 313!
