### ISSUE TITLE
Enhancement Request: Add Harm Values/Range Information to Spark Powers

### ISSUE THREAD

**Issue by thomasech** [trioderegion/nova#2]
Currently, the Powers are just a description. It'd be nice if we could have Harm values on the Powers (and, as such, could use effects/Flares to modify those outputs directly), to make it easier for players to provide their full Harm output on a turn.

**Comment by trioderegion** [comment]
Also fully agreed! 😆 
This and #1 are actually pretty closely related as it involves computing modifications from flares onto powers/sparks.  I would want flare's to be able to increase the Harm/Range of its parent power, which is similar to a flare modifying a sparks attributes.

Definitely slated for the next version (though it may be a little while...).

**Comment by trioderegion** [comment]
Progress is being made. Hang in there 🙂
![image](https://user-images.githubusercontent.com/14878515/167316950-6380def7-c5ed-48c0-b8ef-2008eb720261.png)
