### ISSUE TITLE
UI request - make enemy Variants tickable checkboxes

### ISSUE THREAD

**Issue by megazver** [trioderegion/nova#3]
Pretty much what the title says.

"Showing" the variant, as it works right now, doesn't really _do_ anything. You do that, then unless you take time to mark the token and remember what status effect/marker means what, when those tokens start running around it quickly becomes hard to remember what token is what variant.

If you could tick them after the token has been placed, so you could see it whenever you opened up that particular enemy's sheet, it would be so much more convenient. And if it actually automatically adjusted Health and Harm (like the Heavy variant of Carver, for ex.) and maybe added a prefix to the token name, it would be even better.

Anyway. Have a nice day and thank you for the implementation. I ran a couple of sessions using it and a few minor nitpicks aside it's really good!

**Comment by trioderegion** [comment]
First off, thanks for the kind words and I'm very glad to hear you are enjoying the system, despite its current simplicity.

Secondly, yea...the NPC sheet is basically just a barebones port of the kind of sheet you would use at the table. They need an entire upgrade to turn them into something more "usable" in the VTT -- variants in particular.

On that front, I have good news and bad news. I am currently _deep_ into a complete item overhaul to make the Powers and Flare Mods more full featured (defining harm, range, etc and having mods able to modify fields of the power they are attached to). This will be the 1.1 release, which should hopefully only take another week or two.

AFTER that, I need to give some love to another module of mine (warp gate).

Finally, I can return to Nova for an NPC refactor/upgrade -- 1.2.

Please do file more issues related to sore spots found during play. I have to admit that I havent gotten too many actual play sessions in this system yet (the classic curse of the system dev, haha), so actual play feedback is _invaluable_.

Thanks again :)

**Comment by megazver** [comment]
Thank you!

I ran Nova as a little two-shot to try it out and I'm going to run something else for a while now, so there's no rush. But I'll fiddle with it a bit more and see if I have any more feedback.
