### ISSUE TITLE
Document harm workflow

### ISSUE THREAD

**Issue by finderski** [trioderegion/nova#8]
I'm not sure if this is a problem with v11 or in general (I haven't tried to run this on v10), but targeting an enemy doesn't seem to do anything, because I still need to have the enemy selected before pressing the Apply Harm button, or to set the status, etc.  This was really confusing, because we had things setup to apply damage to the Enemy, but if the player token was selected, the damage would apply to them instead of the enemy and if I, as the GM, tried to apply the Harm by clicking the button but didn't have the enemy selected, it wouldn't do anything either.

Also, not sure if we should be able to target multiple enemies or not, but we were unable to do that, either.

**Comment by trioderegion** [comment]
You've found yet another rough spot in my UX! 😅

Disclaimer, I have not yet tested the system in v11...but it sounds like its mostly working.

Regarding application of damage/statuses, the "Apply Harm" and "Spend Fuel" buttons store information about targeted tokens and work as follows:

1) At any point, if you have a token selected and **left-click** the chat buttons, that action will be applied to the selected token. This is the behavior you are seeing currently.
2) If the power/harm was rolled while that user has tokens targeted, you can **right-click** the apply harm buttons to apply the action to the token(s) targeted when the harm was rolled.  At all points, when a spark uses a power, right clicking the "Spend Fuel" button will spend fuel from the spark that used the power.

For example. A player uses a simple AOE that targets 2 enemies: The player targets those two tokens (T and shift+T to add), rolls the power and the harm and **right-clicks** the "Spend Fuel" button to automatically deduct from their spark (regardless of selection/targets). The GM confirms the action by simply right clicking the "Apply X Harm" button in chat (again, regardless of selection/targets) to apply damage to those enemies.

If for some reason, one of the designated targets is immune or has other effects that modify received harm. The GM can use the "select + left-click" workflow to apply harm to specific tokens.

**All that said, in short**

* Left-click uses selected tokens.
* Right-click uses the player's predefined targets at time of rolling harm.
* Shift+T should allow multiple token targets.

**Comment by finderski** [comment]
Ok, this helps. I’ll mess around with this a bit more. 😀 Thanks for your help. Rich Finder"Nice tuxedo! Nice tuxedo to die in!"On Jun 3, 2023, at 10:37 AM, trioderegion ***@***.***> wrote:﻿
You've found yet another rough spot in my UX! 😅
Disclaimer, I have not yet tested the system in v11...but it sounds like its mostly working.
Regarding application of damage/statuses, the "Apply Harm" and "Spend Fuel" buttons store information about targeted tokens and work as follows:

At any point, if you have a token selected and left-click the chat buttons, that action will be applied to the selected token. This is the behavior you are seeing currently.
If the power/harm was rolled while that user has tokens targeted, you can right-click the apply harm buttons to apply the action to the token(s) targeted when the harm was rolled.  At all points, when a spark uses a power, right clicking the "Spend Fuel" button will spend fuel from the spark that used the power.

For example. A player uses a simple AOE that targets 2 enemies: The player targets those two tokens (T and shift+T to add), rolls the power and the harm and right-clicks the "Spend Fuel" button to automatically deduct from their spark (regardless of selection/targets). The GM confirms the action by simply right clicking the "Apply X Harm" button in chat (again, regardless of selection/targets) to apply damage to those enemies.
If for some reason, one of the designated targets is immune or has other effects that modify received harm. The GM can use the "select + left-click" workflow to apply harm to specific tokens.
All that said, in short

Left-click uses selected tokens.
Right-click uses the player's predefined targets at time of rolling harm.
Shift+T should allow multiple token targets.

**Comment by trioderegion** [comment]
Changing issue for better documentation on the above topic.
